spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true